### ISSUE TITLE
Adiciona Novo Aliado (Inimigo Derrotado)

### ISSUE THREAD

**Issue by amintasvrp** [amintasvrp/Colosseum_of_Champions#10]

**Comment by amintasvrp** [comment]
## Back 
- [x] Remover Champion 
- [x] Adicionar Novo Champion
## Front 
- [x] Remover o Inimigo da lista de Champions
- [x] Adicionar Champion na party do Usuário

**Comment by pabllorsl** [comment]
`void addTeammate();`

Move the defeated enemy to the `team` vector
