### ISSUE TITLE
Vitórias Parciais

### ISSUE THREAD

**Issue by amintasvrp** [amintasvrp/Colosseum_of_Champions#2]

**Comment by amintasvrp** [comment]
## Back
- [x] Checar se o jogador teve uma vitória parcial

##  Front
- [x] *TRUE*: mostrar tela de vitória parcial e encaminhar pra próxima batalha

**Comment by andrerosamatos** [comment]
Tá feito!!! Itamar fez um tantão e eu os ajustes.

**Comment by andrerosamatos** [comment]
Reabrindo por problema na adição do enemy no team (enemy está indo com a vida de boss e não de champion)
