### ISSUE TITLE
Gerar Trio (Randomizado)

### ISSUE THREAD

**Issue by amintasvrp** [amintasvrp/Colosseum_of_Champions#5]

**Comment by amintasvrp** [comment]
Etapas da Tarefa:
## Back
- [x] Randomizar Champion
- [x] Adicionar Champion
- [x] Remover Champion 

## Front
- [x] Realizar o Processo Três Vezes

**Comment by pabllorsl** [comment]
`void createTeam();`

Randomize three champions from the `champions` vector and move them to the `team` vector
