### ISSUE TITLE
Gerar Inimigo (Randomizado)

### ISSUE THREAD

**Issue by amintasvrp** [amintasvrp/Colosseum_of_Champions#6]

**Comment by amintasvrp** [comment]
Tarefas a Realizar:
## Back
- [x] Randomiza Champion
- [x] Remove Champion
- [x] Adiciona Champion

## Front
- [ ] Encapsula em Gerar Inimigo

**Comment by pabllorsl** [comment]
`void createEnemy();`

Randomize a champion from the `champions` vector and move him/her to the `enemy` vector

**Comment by andrerosamatos** [comment]
Itamar concluiu!
