### ISSUE TITLE
Realizar Ataque Normal

### ISSUE THREAD

**Issue by amintasvrp** [amintasvrp/Colosseum_of_Champions#7]

**Comment by amintasvrp** [comment]
## Back
- [x] Calculo do Dano com Vantagem
## Front
- [x] Mostrar a opção ao Usuário
- [x] Realizar Ataque Normal
- [x] Log de combate pós ataque

**Comment by andrerosamatos** [comment]
Concluido, Itamar e eu em parceria.

**Comment by andrerosamatos** [comment]
Concluido, Itamar e eu em parceria.

**Comment by andrerosamatos** [comment]
Reabrindo para ver problema quando ao aumento do dano por causa da vantagem.
