### ISSUE TITLE
Realizar Ataque Especial

### ISSUE THREAD

**Issue by amintasvrp** [amintasvrp/Colosseum_of_Champions#8]

**Comment by amintasvrp** [comment]
## Back
- [x] Calcula Ataque com Vantagem
## Front
- [x] Mostra opção ao Usuário
- [x] Realiza o Ataque Especial
- [x] Mostra log pós ataque

**Comment by andrerosamatos** [comment]
Tá feito

**Comment by andrerosamatos** [comment]
Reabrindo para ver problema quando ao aumento do dano por causa da vantagem.
