### ISSUE TITLE
Situação Atual do Combate

### ISSUE THREAD

**Issue by amintasvrp** [amintasvrp/Colosseum_of_Champions#9]

**Comment by amintasvrp** [comment]
## Front
Os Champions serão caracterizados da seguinte maneira:

- Class = v[0]
- Name = v[1];
- HP = v[2];
- NormalAtk = v[3];
- SpecialAtk = v[4];
- Defense = v[5];

**NormalAtk e SpecialAtk são habilidades ativas, mas Defense é passiva (do Champion)**

**Comment by andrerosamatos** [comment]
Cara, tem que colocar como mensagem Ascii quando o cara ganha a batalha (não o jogo)
